export { F } from './F.js'
export type { Functor } from './customTypes.js'
export { T } from './T.js'
export { classNames } from './classNames.js'
export { compose2 } from './compose2.js'
export { compose3 } from './compose3.js'
export { cond, condU } from './cond.js'
export { constant } from './constant.js'
export { doesPropEq, doesPropEqU } from './doesPropEq.js'
export { filter, filterU } from './filter.js'
export { hasProp, hasPropU } from './hasProp.js'
export { identity } from './identity.js'
export { ifElse, ifElseU } from './ifElse.js'
export { insertAt, insertAtU } from './insertAt.js'
export { isArray } from './isArray.js'
export { isFunction } from './isFunction.js'
export { isFunctor } from './isFunctor.js'
export { isObject } from './isObject.js'
export { lift2, lift2U } from './lift2.js'
export { lift3, lift3U } from './lift3.js'
export { log } from './log.js'
export { map, mapU } from './map.js'
export { mapObject, mapObjectU } from './mapObject.js'
export { omitKeys, omitKeysU } from './omitKeys.js'
export { pickKeys, pickKeysU } from './pickKeys.js'
export { pipe2 } from './pipe2.js'
export { pipe3 } from './pipe3.js'
export { propOr, propOrU } from './propOr.js'
export { reduce, reduceU } from './reduce.js'
export { reduceRight, reduceRightU } from './reduceRight.js'
export { shuffle } from './shuffle.js'
export { sum } from './sum.js'
export { takeN, takeNU } from './takeN.js'
export { unless, unlessU } from './unless.js'
export { when, whenU } from './when.js'
export { zip, zipU } from './zip.js'
