export { F } from './F'
export { Functor } from './customTypes'
export { T } from './T'
export { classNames } from './classNames'
export { compose2 } from './compose2'
export { compose3 } from './compose3'
export { cond, condU } from './cond'
export { constant } from './constant'
export { doesPropEq, doesPropEqU } from './doesPropEq'
export { hasProp, hasPropU } from './hasProp'
export { identity } from './identity'
export { insertAt, insertAtU } from './insertAt'
export { isArray } from './isArray'
export { isFunction } from './isFunction'
export { isFunctor } from './isFunctor'
export { isObject } from './isObject'
export { lift2, lift2U } from './lift2'
export { lift3, lift3U } from './lift3'
export { log } from './log'
export { map, mapU } from './map'
export { mapObject, mapObjectU } from './mapObject'
export { omitKeys, omitKeysU } from './omitKeys'
export { pickKeys, pickKeysU } from './pickKeys'
export { pipe2 } from './pipe2'
export { pipe3 } from './pipe3'
export { propOr, propOrU } from './propOr'
export { reduce, reduceU } from './reduce'
export { reduceRight, reduceRightU } from './reduceRight'
export { shuffle } from './shuffle'
export { sum } from './sum'
export { takeN, takeNU } from './takeN'
export { unless, unlessU } from './unless'
export { when, whenU } from './when'
export { zip, zipU } from './zip'
