name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo under GH workspace
      uses: actions/checkout@v5

    - name: Use nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'npm'

    - name: Install deps without updating package-lock.json
      run: npm ci

    - name: Run the CI build
      run: npm run ci
